(defpackage :functions-and-relations
  (:use
   :cl
   :technicals
   :universal-algebra)
  (:export
   :relation
   :relation-p
   :valid-graph-p
   :make-relation
   :malformed-relation-definition
   :source
   :target
   :graph
   :algebraic-function
   :make-function
   :function-graph-p
   :function-to-graph
   :apply-function-to-element
   :apply-function-to-tuple
   :apply-function-to-set
   :range
   :surjective-p
   :injective-p
   :homomorphism-p
   :isomorphism-p
   :quasi-homomorphism-p
   :apply-quasihomomorphism-to-algebra
   :no-quasihomomorphism))
