(defpackage :fundamental-functions
 (:use :cl :technicals)
 (:export
   :relation
   :relation-p
   :valid-graph-p
   :make-relation
   :malformed-relation-definition
   :source
   :target
   :graph
   :algebraic-function
   :equal-pred
   :algebraic-function-p
   :make-function
   :malformed-function-definition
   :function-graph-p
   :function-to-graph
   :apply-function-to-element
   :apply-function-to-tuple
   :apply-function-to-set
   :range
   :surjective-p
   :injective-p
   :bijective-p
   :function-error
   :kernel
   :inverse-image
   :inverse-image-of-element
   :iterate-over-function-graph
   :value-of-element
   :all-operands
   :nth-operand
   :function-symbol-of
   :implementing-function-of
   :get-arity-of-table
   :arity-of-function
   :restrict-function-on-source-and-target
   :restrict-function-on-target
   :restrict-function-on-source))
