#!/bin/sh
if test -z "$1" -o -z "$2"; then
	echo "?? cg A p [log_level or 'p'] computes Cg(p) in A"
	echo "   (needs A.alg, p.br, creates p.cg)."
	echo "   If A.con exists, then displays congruence number.";
else
	echo \\begin_command > $1.par
	echo \\generate_congruence >> $1.par
	echo \\algebra_file{$1.alg} >> $1.par
	echo \\vectorlist_file{$2.br} >> $1.par
	echo \\output_file{$2.cg} >> $1.par
	echo \\end_command >> $1.par
	if test -e $1.con; then
		echo %% >> $1.par
		echo \\begin_command >> $1.par
		echo \\find_congruence_number >> $1.par
		echo \\conlist_file{$1.con} >> $1.par
		echo \\congruence{\\conlist_file{$2.cg}\\number{0}} >> $1.par
		echo \\end_command >> $1.par
	fi;
	if test "$3" = "p"; then
		echo $1.par created.;
	else
		uab $1 $3;
	fi;
fi
