#!/bin/sh
if test -z "$1"; then
	echo "?? findone A [log_level or 'p'] finds one_congruence in Con(A)"
	echo "   (needs A.con, 1_A's # is displayed).";
else
	echo \\begin_command > $1.par
	echo \\find_congruence_number >> $1.par
	echo \\conlist_file{$1.con} >> $1.par
	echo \\congruence{\\one_congruence{}} >> $1.par
	echo \\end_command >> $1.par
	if test "$2" = "p"; then
		echo $1.par created.;
	else
		uab $1 $2;
	fi;
fi
