#!/bin/sh
if test -z "$1" -o -z "$2" -o -z "$3" -o -z "$4"; then
	echo "?? prc A P n m [log_level or 'p'] creates n x m on P \le A x A, where"
	echo "   n, m is a number, or 'one', or 'zero'"
	echo "   (needs A.con, P.uni, P.con, creates P.cg, its # is displayed).";
else
	echo \\begin_command > $2.par
	echo \\product_congruence >> $2.par
	echo \\vectorlist_file{$2.uni} >> $2.par
	if test "$3" = "one"; then
		echo \\congruence{\\one_congruence{}} >> $2.par;
	elif test "$3" = "zero"; then
		echo \\congruence{\\zero_congruence{}} >> $2.par;
	else
		echo \\congruence{\\conlist_file{$1.con}\\number{$3}} >> $2.par;
	fi
	if test "$4" = "one"; then
		echo \\congruence{\\one_congruence{}} >> $2.par;
	elif test "$4" = "zero"; then
		echo \\congruence{\\zero_congruence{}} >> $2.par;
	else
		echo \\congruence{\\conlist_file{$1.con}\\number{$4}} >> $2.par;
	fi

	echo \\output_file{$2.cg} >> $2.par
	echo \\end_command >> $2.par
	echo %% >> $2.par
	echo \\begin_command >> $2.par
	echo \\find_congruence_number >> $2.par
	echo \\conlist_file{$2.con} >> $2.par
	echo \\congruence{\\conlist_file{$2.cg}\\number{0}} >> $2.par
	echo \\end_command >> $2.par
	if test "$5" = "p"; then
		echo $2.par created.;
	else
		uab $2 $5;
	fi;
fi
