/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uacalc_Compute */

#ifndef _Included_uacalc_Compute
#define _Included_uacalc_Compute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uacalc_Compute
 * Method:    run_uab
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_uacalc_Compute_run_1uab
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     uacalc_Compute
 * Method:    stop_uab
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uacalc_Compute_stop_1uab
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
